name: Deploy Example
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys and deploy new version on the server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "--------- Adding SSH keys and configuring the target host"
          mkdir -p ~/.ssh
          echo -e "HashKnownHosts no
          Host *
            ForwardAgent yes
            ServerAliveInterval 60
            ServerAliveCountMax 40
            StrictHostKeyChecking no
          Host target
            User ci
            HostName "${{ secrets.DEPLOY_SERVER }}" 
            Port 22" >> ~/.ssh/config
            
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DEPLOY_KEY_PRODUCTION }}"

          echo "------------------------ Parse variables to files"
          sudo groupadd devs
          sudo usermod -aG devs `whoami`  
          sudo chown :devs -R .

          echo "---------- Deploying to production servers"
          echo "----------- Create dir on server"
          ssh target "mkdir -p $ROOT_FOLDER $RELEASE_FOLDER/release_$GITHUB_SHA/"
          scp -r ./* target:$RELEASE_FOLDER/release_$GITHUB_SHA/

          echo "----------- Deploy on server"
          ssh target "bash -s" < \
          ./scripts/deploy-website.sh /data/www/example.com release_$GITHUB_SHA
    env:
      ROOT_FOLDER: /data/www/example.com
      RELEASE_FOLDER: /data/www/example.com/releases
